name: rspec tests

on: [pull_request]

jobs:
  rspec:
    name: Rspec
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports: ["5432:5432"]
        env:
          POSTGRES_DB: project_resource_search_test
          POSTGRES_USER: cidbuser
          POSTGRES_PASSWORD: postgres

    steps:
      - uses: actions/checkout@v2

      - id: setup
        uses: ./.github/actions/setup-project

      - name: "Precompile assets"
        shell: bash
        env:
          RAILS_ENV: ${{ inputs.rails_env }}
          SECRET_KEY_BASE: not-actually-secret
        run: bundle exec rake assets:precompile

      - name: Run rspec
        env:
          DATABASE_URL: ${{ steps.setup.outputs.database_url }}
        run: bundle exec rspec
